apiVersion: v1
kind: Service
metadata:
  name: {{ template "novnc.fullname" . }}
  labels:
    app: {{ template "novnc.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- if (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceExternalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: httpnv
  ports:
    - name: vnc
      port: 5901
      targetPort: rvnc
  ports:
    - name: rssh
      port: 22
      targetPort: ssh
  selector:
    app: {{ template "novnc.fullname" . }}
